[package]
name = "aptos-gas-tracker"
version = "1.0.0"
authors = []

[addresses]
gas_tracker = "0x61f8783cbbac0b4e00c728fd2eac8fad7da48adfdb71dca6020efd9f5fa39a86"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
